version: "3"
services:
  smahub:
    build: .
    container_name: smahub
#    network_mode: "host"
    restart: unless-stopped
    # forward python debug server port - not necessary with network_mode: "host"
    ports:
      - 5678:5678
    environment:
      - TZ=Europe/Berlin
      - MQTT_ENABLED=true
      - MQTT_ADDRESS=mosquitto
      - MQTT_PORT=1883
      - MQTT_USER=smahub
      - MQTT_PASSWORD=smahub
      - SHM2_ENABLED=true
      - HA_MQTT_ENABLED=true
      - HA_MQTT_ADDRESS=homeassistant
   networks:
     - backbone
networks:
  backbone:
    name: smarthomelocal
    external: true
